apiVersion: app/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
    template:
      metadata:
        labels:
          app: auth
      spec:
        containers:
          - name: auth
            image: pensiveeagle/kub-net-demo:auth-api-1
            imagePullPolicy: Always